### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by jeffdfield** [JohnRoos/PowerShell#8]
I may be using the credential object incorrectly but this is what I'm getting.

`
$OSDStats | Write-ObjectToSQL -Credential $mycreds -Server S021M370.AUTOEXPR.COM -Database GI_Imaging_Baseline2 -TableName TSBaseLine

PS C:\Users\USER\Desktop> C:\Users\USER\Desktop\OSD Time Stats v1.1.ps1
WARNING: Could not open the connection. See error message below3.
Write-ObjectToSQL : Exception calling "Open" with "0" argument(s): "Login failed for user 'Domain\ACCOUNT'."
At C:\Users\USER\Desktop\OSD Time Stats v1.1.ps1:104 char:13
+ $OSDStats | Write-ObjectToSQL -Credential $mycreds -Server S021M370.A ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-ObjectToSQL`

**Comment by JohnRoos** [comment]
When the credential parameter is used in Write-ObjectToSQL, the function will attempt to use a SQL Server account rather than a windows account.
Could it be that you are trying to use credentials for a windows account? That is not what its designed for. Instead, try to use a SQL Server account, or run the script as a windows user with permissions to the database.

**Comment by jeffdfield** [comment]
I can't remember what fixed this but I did fix it. Thanks for the response!
